---
title: "Cofee rust"
autor: "José Enrique Espitia López"
date: 21/05/2025
format: 
  html:
    toc: true
    theme: default
warning: false
message: false
---

Apressentação

O conjunto de dados será o da ferrugem do café na Etiopia que esta no arquivo de dados na nuvem.

# Importar os dados

Usaremos a função `gsheet2tbl()` do pacote **\[gsheet\]** para carregar os dados no ambiente

```{r}
library(gsheet)
cr <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit?gid=1871397229#gid=1871397229")
```

# Visualiza os dados

Usaremos a função `datatable()`

```{r}
#install.packages("DT") #para tabela interativa
library(DT)
datatable(cr)
```

# Graficos

```{r}
library(tidyverse)

cr|>
  ggplot(aes(lon, lat)) +
  geom_point()

library(rnaturalearth)
library(rnaturalearthhires)
library(remotes)
remotes::install_github("ropensci/rnaturalearthhires")
ETH <- ne_states(country = "Ethiopia",
                 returnclass = "sf")

library(tidyverse)
library(ggspatial)

ETH|>
ggplot()+
  geom_sf(fill = "white") +
  geom_point(data= cr, aes(lon, lat, color= inc)) +
  scale_color_viridis_c()+
  theme_minimal()+
  theme(legend.position = "bottom")+
  annotation_scale(location = "tl") +
  annotation_north_arrow(location = "br", which_north = "true")+
  labs(title = "ferrugem do café na Etiópia",
       x = "longitude", y = "latitude",
       subtitle = "levanta",
       caption = "Fonye: Del Ponte et al. (2025)",
       color = "incidencia (%)")

ggsave("mapa_ethiopia.png", bg = "white", width = 10)
```
